import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { AuditLogEntity } from '../../database/entities/audit-log.entity.js';

export interface CreateAuditLogOptions {
    action: string;
    resource: string;
    resourceId?: string;
    details?: Record<string, unknown>;
    userId?: string;
    organizationId: string;
    ipAddress?: string;
    userAgent?: string;
}

@Injectable()
export class AuditService {
    constructor(
        @InjectRepository(AuditLogEntity)
        private readonly auditRepo: Repository<AuditLogEntity>,
    ) { }

    /** Create a new audit log entry */
    async log(opts: CreateAuditLogOptions): Promise<void> {
        const entry = this.auditRepo.create({
            action: opts.action,
            resource: opts.resource,
            resourceId: opts.resourceId,
            details: opts.details ? JSON.stringify(opts.details) : undefined,
            userId: opts.userId,
            organizationId: opts.organizationId,
            ipAddress: opts.ipAddress,
            userAgent: opts.userAgent,
        });
        await this.auditRepo.save(entry);
    }

    /**
     * Return all audit logs for the given organization (SUPER_ADMIN / ORG_ADMIN).
     */
    async findAllForOrg(organizationId: string): Promise<AuditLogEntity[]> {
        return this.auditRepo.find({
            where: { organizationId },
            order: { createdAt: 'DESC' },
            relations: ['user'],
            select: {
                id: true,
                action: true,
                resource: true,
                resourceId: true,
                details: true,
                ipAddress: true,
                userAgent: true,
                userId: true,
                organizationId: true,
                createdAt: true,
                user: {
                    id: true,
                    email: true,
                    name: true,
                    role: true,
                },
            },
        });
    }

    /**
     * Return audit logs generated by a specific user within their organization.
     */
    async findForUser(
        userId: string,
        organizationId: string,
    ): Promise<AuditLogEntity[]> {
        return this.auditRepo.find({
            where: { userId, organizationId },
            order: { createdAt: 'DESC' },
        });
    }
}
